version: "3.3"

volumes:
  postgres-data:
  cloud-beaver-data:

services:
  db:
    container_name: postgresql
    image: postgres:15.8-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  gui:
    restart: unless-stopped
    hostname: cloudbeaver
    image: dbeaver/cloudbeaver
    volumes:
      - cloud-beaver-data:/opt/cloudbeaver/workspace
    ports:
      - "8978:8978"
    depends_on:
      - db